basePath: api/v1
host: localhost:8000
info:
  contact:
    email: dwikurnianto.mulyadien@gmail.com
    name: Meruya Technology Founder
  description: Authentications api with OAuth2
  title: OAuth2 API
  version: "1.0"
paths: {}
swagger: "2.0"
