basePath: /
host: localhost:8080
info:
  contact:
    email: dwikurnianto.mulyadien@gmail.com
    name: Meruya Technology Founder
  description: This is a sample service for managing User
  license:
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Example API
  version: "1.0"
paths: {}
swagger: "2.0"
